# Generated by Django 4.2 on 2026-06-17 22:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(db_column='id_mesa', primary_key=True, serialize=False)),
                ('numero_mesa', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('capacidad', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('estado', models.CharField(choices=[('libre', 'Libre'), ('ocupada', 'Ocupada'), ('esperando_pago', 'Esperando pago'), ('pagada', 'Pagada'), ('en_limpieza', 'En limpieza'), ('bloqueada', 'Bloqueada')], default='libre', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_ocupacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_solicitud_pago', models.DateTimeField(blank=True, null=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('fecha_liberacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('asignado_en', models.DateTimeField(blank=True, null=True)),
                ('mesero_asignado', models.ForeignKey(blank=True, db_column='id_mesero_asignado', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesas_atendidas', to='domain.usuario')),
                ('pedido_actual', models.ForeignKey(blank=True, db_column='id_pedido_actual', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesas_operativas', to='domain.pedidoencabezado')),
                ('usuario_actual', models.ForeignKey(blank=True, db_column='id_usuario_actual', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesas_asignadas', to='domain.usuario')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'db_table': 'mesas',
                'ordering': ['numero_mesa', 'id'],
            },
        ),
    ]
