# Generated by Django 4.2 on 2026-06-17 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.TextField(blank=True, null=True)),
                ('fecha_accion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bitácora',
                'verbose_name_plural': 'Bitácoras',
                'db_table': 'bitacora',
            },
        ),
        migrations.CreateModel(
            name='CalificacionCliente',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion_comida', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('calificacion_servicio', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('calificacion_ambiente', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_calificacion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Calificacion',
                'verbose_name_plural': 'Calificaciones',
                'db_table': 'calificaciones_clientes',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_cate', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cate', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='MensajeChat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('remitente', models.CharField(max_length=50)),
                ('destinatario', models.CharField(max_length=50)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'db_table': 'mensajes_chat',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id_menu', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_menu', models.CharField(blank=True, max_length=300, null=True)),
                ('descripcion_menu', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Menú',
                'verbose_name_plural': 'Menús',
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id_musica', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_musica', models.CharField(blank=True, max_length=100, null=True)),
                ('artista_musica', models.CharField(blank=True, max_length=100, null=True)),
                ('duracion_musica', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Música',
                'verbose_name_plural': 'Músicas',
                'db_table': 'musica',
            },
        ),
        migrations.CreateModel(
            name='NotificacionCliente',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=120)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(default='general', max_length=30)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones_clientes',
                'ordering': ['-fecha_envio', '-id_notificacion'],
            },
        ),
        migrations.CreateModel(
            name='PedidoDetalle',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('id_producto', models.BigIntegerField(blank=True, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedido',
                'db_table': 'pedido_detalle',
            },
        ),
        migrations.CreateModel(
            name='PedidoEncabezado',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('id_restaurante', models.IntegerField(blank=True, null=True)),
                ('tipo_pedido', models.CharField(choices=[('restaurante', 'Restaurante'), ('para_llevar', 'Para llevar')], default='restaurante', max_length=20)),
                ('fecha_pedido', models.DateField(blank=True, null=True)),
                ('total_pedido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado_pedido', models.CharField(choices=[('abierto', 'Abierto'), ('en_preparacion', 'En preparacion'), ('listo_para_recoger', 'Listo para recoger'), ('entregado', 'Entregado'), ('pagado', 'Pagado'), ('finalizado', 'Finalizado')], default='abierto', max_length=20)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedido_encabezado',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_permiso', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'permisos',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(blank=True, max_length=300, null=True)),
                ('precio_producto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descripcion_producto', models.CharField(blank=True, max_length=300, null=True)),
                ('id_res', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reser', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(blank=True, max_length=120, null=True)),
                ('id_res', models.IntegerField(blank=True, null=True)),
                ('fecha_reser', models.DateField(blank=True, null=True)),
                ('estado_reser', models.CharField(blank=True, choices=[('activa', 'Activa'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], max_length=12, null=True)),
                ('hora_reser', models.CharField(blank=True, max_length=5, null=True)),
                ('detalle_evento', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reservas',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'rol_permisos',
            },
        ),
        migrations.CreateModel(
            name='SolicitudMusica',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('cancion', models.CharField(blank=True, max_length=150, null=True)),
                ('artista', models.CharField(blank=True, max_length=150, null=True)),
                ('posicion_orden', models.PositiveIntegerField(blank=True, null=True)),
                ('duracion_segundos', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio_reproduccion', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_eliminacion', models.TextField(blank=True, null=True)),
                ('id_res', models.IntegerField(blank=True, null=True)),
                ('estado_solicitud', models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('reproduciendo', 'Reproduciendo'), ('reproducida', 'Reproducida'), ('eliminada', 'Eliminada')], default='pendiente', max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Solicitud de Música',
                'verbose_name_plural': 'Solicitudes de Música',
                'db_table': 'solicitud_musica',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('clave', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_usuario', models.CharField(blank=True, choices=[('cliente', 'Cliente'), ('administrador', 'Administrador'), ('trabajador', 'Trabajador'), ('mesero', 'Mesero')], max_length=20, null=True)),
                ('estado', models.CharField(default='Activo', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('id_rol', models.ForeignKey(blank=True, db_column='id_rol', null=True, on_delete=django.db.models.deletion.SET_NULL, to='domain.rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='SolicitudPago',
            fields=[
                ('id_solicitud_pago', models.AutoField(primary_key=True, serialize=False)),
                ('metodo_pago', models.CharField(max_length=40)),
                ('estado', models.CharField(default='pendiente', max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('atendido_por', models.ForeignKey(blank=True, db_column='id_mesero_atendio', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_pago_atendidas', to='domain.usuario')),
                ('id_pedido', models.ForeignKey(blank=True, db_column='id_pedido', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='domain.pedidoencabezado')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_pago_cliente', to='domain.usuario')),
            ],
            options={
                'verbose_name': 'Solicitud de pago',
                'verbose_name_plural': 'Solicitudes de pago',
                'db_table': 'solicitudes_pago',
                'ordering': ['-fecha_creacion', '-id_solicitud_pago'],
            },
        ),
    ]
