# Generated by Django 4.2 on 2026-06-17 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domain', '0001_initial'),
        ('modules_mesas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpago',
            name='mesa',
            field=models.ForeignKey(blank=True, db_column='mesa_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_pago', to='modules_mesas.mesa'),
        ),
        migrations.AddField(
            model_name='solicitudmusica',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, db_column='eliminado_por_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_musica_eliminadas', to='domain.usuario'),
        ),
        migrations.AddField(
            model_name='solicitudmusica',
            name='id_musica',
            field=models.ForeignKey(blank=True, db_column='id_musica', null=True, on_delete=django.db.models.deletion.SET_NULL, to='domain.musica'),
        ),
        migrations.AddField(
            model_name='solicitudmusica',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='domain.usuario'),
        ),
        migrations.AddField(
            model_name='solicitudmusica',
            name='mesa',
            field=models.ForeignKey(blank=True, db_column='mesa_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_musica', to='modules_mesas.mesa'),
        ),
        migrations.AddField(
            model_name='rolpermiso',
            name='id_permiso',
            field=models.ForeignKey(db_column='id_permiso', on_delete=django.db.models.deletion.CASCADE, to='domain.permiso'),
        ),
        migrations.AddField(
            model_name='rolpermiso',
            name='id_rol',
            field=models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, to='domain.rol'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='domain.usuario'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='mesa',
            field=models.ForeignKey(blank=True, db_column='mesa_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='modules_mesas.mesa'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_cate',
            field=models.ForeignKey(blank=True, db_column='id_cate', null=True, on_delete=django.db.models.deletion.SET_NULL, to='domain.categoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_menu',
            field=models.ForeignKey(blank=True, db_column='id_menu', null=True, on_delete=django.db.models.deletion.SET_NULL, to='domain.menu'),
        ),
        migrations.AddField(
            model_name='pedidoencabezado',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='domain.usuario'),
        ),
        migrations.AddField(
            model_name='pedidoencabezado',
            name='mesa',
            field=models.ForeignKey(blank=True, db_column='mesa_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='modules_mesas.mesa'),
        ),
        migrations.AddField(
            model_name='pedidodetalle',
            name='id_pedido',
            field=models.ForeignKey(blank=True, db_column='id_pedido', null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.pedidoencabezado'),
        ),
        migrations.AddField(
            model_name='notificacioncliente',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='domain.usuario'),
        ),
        migrations.AddField(
            model_name='calificacioncliente',
            name='id_pedido',
            field=models.ForeignKey(blank=True, db_column='id_pedido', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='domain.pedidoencabezado'),
        ),
        migrations.AddField(
            model_name='calificacioncliente',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='domain.usuario'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='domain.usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='rolpermiso',
            unique_together={('id_rol', 'id_permiso')},
        ),
        migrations.AddConstraint(
            model_name='calificacioncliente',
            constraint=models.UniqueConstraint(fields=('id_pedido',), name='calificaciones_unica_por_pedido'),
        ),
    ]
